// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZpD7tWO02MEJv5VMphU82aC3dt_RUCjs',
    appId: '1:416774545611:web:0d6fd58723dc987b997b4e',
    messagingSenderId: '416774545611',
    projectId: 'aptech-it-support',
    authDomain: 'aptech-it-support.firebaseapp.com',
    storageBucket: 'aptech-it-support.firebasestorage.app',
    measurementId: 'G-EGMFY8YY7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm62nhKk9p4SjiGZ04VcmktnRXgIorKxg',
    appId: '1:416774545611:android:bf82fa07363954db997b4e',
    messagingSenderId: '416774545611',
    projectId: 'aptech-it-support',
    storageBucket: 'aptech-it-support.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZpD7tWO02MEJv5VMphU82aC3dt_RUCjs',
    appId: '1:416774545611:web:63c889c71ca629f7997b4e',
    messagingSenderId: '416774545611',
    projectId: 'aptech-it-support',
    authDomain: 'aptech-it-support.firebaseapp.com',
    storageBucket: 'aptech-it-support.firebasestorage.app',
    measurementId: 'G-HCM8QLPER2',
  );

}